Hero header fixes
front-end-by-rimantas/18-grupe-portfolio-elvish pull request #38
Opened 2020-10-13 07:22 UTC by ugniusnor

hero header some fixes,
Back to top button added
scrol from top added

2020-10-13 18:23 UTC, mildasuziedelyte commented on js/components/back-to-top/scrollToTop.js
> +        console.log("labas");
šitą prie progos už'hidink : )

2020-10-13 18:26 UTC, mildasuziedelyte commented on js/components/header/scrollToTop.js
> +export default scrollTop;
nesuprantu kodėl ir folder'yje header ir back-to-top yra ta pati funkcija scrollTop, čia viskas ok?

2020-10-13 18:28 UTC, mildasuziedelyte commented on js/components/hero/heroSandwich.js
> +import headerFixes from "../header/headerFixes.js";
o ką daro headerFixes? čia nieko nereikia koreguoti, šiaip įdomu : )

2020-10-13 18:29 UTC, mildasuziedelyte requested changes
Pažiūrėki komentarus, tikrai neesminiai : ) tai gal labai taisyt kažko ir nereikės, bet dėl visa ko.

2020-10-14 06:22 UTC, ugniusnor commented on js/components/back-to-top/scrollToTop.js
> +        console.log("labas");
done

2020-10-14 06:25 UTC, ugniusnor commented on js/components/hero/heroSandwich.js
> +import headerFixes from "../header/headerFixes.js";
Sutvarko burgerio spalva kai ja scrolini i virsu arba i apacia, priklasomai nuo ekrano aukscio, ateityje ten dar jauciu bus galima papildyt mazais fixais, (pvz taskelius pakoreguot headeryje ar pan), kad neapkraut pagrindiniu funckicu daug prirarasnt, bet tuo paciu ir nekuriant dar 100 JS failu. Gal pavadinimas ne tobulas

2020-10-14 06:25 UTC, ugniusnor commented on js/components/header/scrollToTop.js
> +export default scrollTop;
Cia tikriausiai po visu musu pullu mergu, atsirado, arba gal tu netycia du kart nukopijavai? Nezinau, bet istryniau viena

2020-10-14 06:39 UTC, UrteZ commented on js/main.js
> +import HeroScroll from "./scrollFromHero.js"
neturetu buti is mazosios heroScroll? cia tik del bendros tvarkos :) (ir visur kitur pakeisti)

2020-10-14 07:04 UTC, Karina-N approved these changes
All seems good now after changes

2020-10-14 07:05 UTC, mildasuziedelyte approved these changes

2020-10-14 07:06 UTC, UrteZ approved these changes

2020-10-14 07:06 UTC, merged