Education update u
front-end-by-rimantas/18-grupe-portfolio-elvish pull request #62
Opened 2020-10-15 07:06 UTC by UrteZ

2020-10-15 18:34 UTC, mildasuziedelyte submitted a review, later dismissed
keep on good work! : )

2020-10-16 07:55 UTC, ugniusnor requested changes
Viskas atrodo super! 
Kabinėjuos prie neesminiu dąlykų kurie nieko nekeičia. Bet ištrink is layout.css ta display:flex (106 eilutė), nes poto ir grius visas layoutais jeigu ten pripaniosim klaidu arba nereikalingu dalyku , o ji istrynus visur display:block turetu tapt nebereikalingi
Jeigu kur nusisnekejau tai sakyk  🤷‍♂️

2020-10-16 07:55 UTC, ugniusnor commented on css/layout.css
> +            .row.edu-top-section {
Šitas parametras tikrai nereikalingas, nes tu jį paskui perašai custom.css'e
Ir į layout'ą display parametru sekcijos dėti turbūt nereiktų, nes pasimes, o custom jį vistiek overwritina

2020-10-16 07:55 UTC, ugniusnor commented on css/custom.css
> +    display: block;
Mna regis jis ir taip display:block, todėl šita savybė nelabai reikalinga (su sąlyga, kad display:flex bus ištrintas iš layout css)

2020-10-16 07:55 UTC, ugniusnor commented on css/custom.css
> +        display: block;
nereikalinga sąvybė

2020-10-16 09:09 UTC, UrteZ commented on css/layout.css
> +            .row.edu-top-section {
istryniau :)

2020-10-16 09:09 UTC, UrteZ commented on css/custom.css
> +    display: block;
pakeiciau :) ir aciu, pagavau dabar kaip veikia sitie parametrai :)

2020-10-16 09:10 UTC, UrteZ commented on css/custom.css
> +        display: block;
istryniau :)

2020-10-16 09:35 UTC, ugniusnor approved these changes

2020-10-16 09:41 UTC, mildasuziedelyte approved these changes

2020-10-18 10:27 UTC, belauzas commented
Auč... konfliktai... 👀⚠🌹

2020-10-19 07:57 UTC, closed without merging