Fixing header
front-end-by-rimantas/18-grupe-portfolio-elvish pull request #73
Opened 2020-10-26 10:53 UTC by ugniusnor

2020-10-26 12:09 UTC, mildasuziedelyte requested changes
Šiaip viskas atrodo gerai, gal tik tą to-top pakeiskim į ikonėlę? nes stilius lyg css'e liko : )

2020-10-26 12:09 UTC, mildasuziedelyte commented on index.html
> +    <div class="to-top">^</div>
Gal visgi šitą įdėkim, kad gražiau būtų?
<i class="fa fa-angle-up"></i>

2020-10-27 10:59 UTC, mildasuziedelyte approved these changes

2020-10-27 15:26 UTC, Karina-N approved these changes

2020-10-28 07:56 UTC, UrteZ approved these changes

2020-10-28 08:01 UTC, merged